plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.9.24'
    id 'java'
    id 'application'
}

group 'com.uliaid.kotlin'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.2'
}

application {
    mainClass = 'com.uliaid.personalbranding.MainKt'
}

test {
    useJUnitPlatform()
}
